apiVersion: v1
kind: Service
metadata:
  name: nginxservice
  labels:
    name: nginxservice
spec:
  ports:
    - port: 80
      nodePort: 30225
      protocol: TCP
  selector:
    app: frontend
  type: NodePort
